-- MySQL Script generated by MySQL Workbench
-- Wed Dec  4 18:40:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ERP-Micro
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ERP-Micro` ;

-- -----------------------------------------------------
-- Schema ERP-Micro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ERP-Micro` DEFAULT CHARACTER SET utf8mb4 ;
USE `ERP-Micro` ;

-- -----------------------------------------------------
-- Table `ERP-Micro`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`account` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`account` (
  `account_code` VARCHAR(7) NOT NULL,
  `account_name` VARCHAR(45) NOT NULL,
  `debit_credit_indicator` ENUM('Debit', 'Credit') NOT NULL,
  `account_type` ENUM('Assets', 'Liabilities', 'Equity', 'Income', 'Expenses') NOT NULL,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`account_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`account_period`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`account_period` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`account_period` (
  `account_period_ID` VARCHAR(7) NOT NULL,
  `fiscal_year` VARCHAR(4) NOT NULL,
  `period_name` VARCHAR(45) NULL DEFAULT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `is_closed` TINYINT NOT NULL,
  PRIMARY KEY (`account_period_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`departments` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`departments` (
  `dept_ID` VARCHAR(7) NOT NULL,
  `dept_name` VARCHAR(10) NOT NULL,
  `upper_dept_ID` VARCHAR(7) NULL DEFAULT NULL,
  PRIMARY KEY (`dept_ID`),
  INDEX `upper_dept_ID` (`upper_dept_ID` ASC) VISIBLE,
  CONSTRAINT `departments_ibfk_1`
    FOREIGN KEY (`upper_dept_ID`)
    REFERENCES `ERP-Micro`.`departments` (`dept_ID`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`journal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`journal` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`journal` (
  `journal_ID` VARCHAR(7) NOT NULL,
  `total_debit` DECIMAL(10,2) NOT NULL,
  `total_credit` DECIMAL(10,2) NOT NULL,
  `dept_ID` VARCHAR(7) NOT NULL,
  `is_approved` TINYINT NOT NULL,
  PRIMARY KEY (`journal_ID`),
  INDEX `dept_ID` (`dept_ID` ASC) VISIBLE,
  CONSTRAINT `journal_ibfk_1`
    FOREIGN KEY (`dept_ID`)
    REFERENCES `ERP-Micro`.`departments` (`dept_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`employee` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`employee` (
  `employee_ID` VARCHAR(7) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `current_dept` VARCHAR(8) NOT NULL,
  `current_position` VARCHAR(20) NOT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`employee_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`approval`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`approval` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`approval` (
  `approval_ID` VARCHAR(7) NOT NULL,
  `journal_ID` VARCHAR(7) NOT NULL,
  `status` ENUM('Pending', 'Approved', 'Rejected') NOT NULL,
  `approved_date` DATE NULL DEFAULT NULL,
  `approver_ID` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`approval_ID`),
  INDEX `journal_ID` (`journal_ID` ASC) VISIBLE,
  INDEX `fk_approval_employee1_idx` (`approver_ID` ASC) VISIBLE,
  CONSTRAINT `approval_ibfk_1`
    FOREIGN KEY (`journal_ID`)
    REFERENCES `ERP-Micro`.`journal` (`journal_ID`),
  CONSTRAINT `fk_approval_employee1`
    FOREIGN KEY (`approver_ID`)
    REFERENCES `ERP-Micro`.`employee` (`employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`attendance` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`attendance` (
  `attendance_ID` VARCHAR(7) NOT NULL,
  `employee_ID` VARCHAR(7) NOT NULL,
  `date` DATE NOT NULL,
  `start_time` TIME NULL DEFAULT NULL,
  `end_time` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`attendance_ID`),
  INDEX `employee_ID` (`employee_ID` ASC) VISIBLE,
  CONSTRAINT `attendance_ibfk_1`
    FOREIGN KEY (`employee_ID`)
    REFERENCES `ERP-Micro`.`employee` (`employee_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`bank_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`bank_account` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`bank_account` (
  `bank_account_ID` VARCHAR(7) NOT NULL,
  `account_name` VARCHAR(10) NOT NULL,
  `bank_name` VARCHAR(10) NOT NULL,
  `account_number` VARCHAR(45) NOT NULL,
  `is_active` SMALLINT NOT NULL,
  PRIMARY KEY (`bank_account_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`basic_salary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`basic_salary` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`basic_salary` (
  `salary_ID` VARCHAR(7) NOT NULL,
  `employee_ID` VARCHAR(7) NOT NULL,
  `salary` DECIMAL(10,2) NOT NULL,
  `salary_month` DATE NOT NULL,
  PRIMARY KEY (`salary_ID`),
  INDEX `employee_ID` (`employee_ID` ASC) VISIBLE,
  CONSTRAINT `basic_salary_ibfk_1`
    FOREIGN KEY (`employee_ID`)
    REFERENCES `ERP-Micro`.`employee` (`employee_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`project` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`project` (
  `project_ID` VARCHAR(7) NOT NULL,
  `project_name` VARCHAR(20) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`project_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`budget`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`budget` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`budget` (
  `budget_ID` VARCHAR(7) NOT NULL,
  `dept_ID` VARCHAR(7) NOT NULL,
  `project_ID` VARCHAR(7) NOT NULL,
  `account_period_ID` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`budget_ID`),
  INDEX `project_ID` (`project_ID` ASC) VISIBLE,
  INDEX `account_period_ID` (`account_period_ID` ASC) VISIBLE,
  INDEX `dept_ID` (`dept_ID` ASC) VISIBLE,
  CONSTRAINT `budget_ibfk_1`
    FOREIGN KEY (`project_ID`)
    REFERENCES `ERP-Micro`.`project` (`project_ID`),
  CONSTRAINT `budget_ibfk_2`
    FOREIGN KEY (`account_period_ID`)
    REFERENCES `ERP-Micro`.`account_period` (`account_period_ID`),
  CONSTRAINT `budget_ibfk_3`
    FOREIGN KEY (`dept_ID`)
    REFERENCES `ERP-Micro`.`departments` (`dept_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`customer` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`customer` (
  `customer_id` VARCHAR(7) NOT NULL,
  `customer_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `refund_account` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`employee_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`employee_detail` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`employee_detail` (
  `employee_ID` VARCHAR(7) NOT NULL,
  `resident_number` CHAR(13) NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `cellphone` VARCHAR(15) NULL DEFAULT NULL,
  `bank_account` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`employee_ID`),
  CONSTRAINT `employees_detail_ibfk_1`
    FOREIGN KEY (`employee_ID`)
    REFERENCES `ERP-Micro`.`employee` (`employee_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`factory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`factory` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`factory` (
  `factory_id` VARCHAR(7) NOT NULL,
  `factory_name` VARCHAR(255) NOT NULL,
  `factory_phone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`factory_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`product` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`product` (
  `product_id` VARCHAR(7) NOT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `product_category` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  `manufacture_date` DATE NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`warehouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`warehouse` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`warehouse` (
  `warehouse_id` VARCHAR(7) NOT NULL,
  `warehouse_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`warehouse_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`inventory` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`inventory` (
  `product_id` VARCHAR(7) NOT NULL,
  `warehouse_id` VARCHAR(7) NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`product_id`, `warehouse_id`),
  INDEX `fk_inventory_warehouse1_idx` (`warehouse_id` ASC) VISIBLE,
  CONSTRAINT `inventory_management_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ERP-Micro`.`product` (`product_id`),
  CONSTRAINT `fk_inventory_warehouse1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `ERP-Micro`.`warehouse` (`warehouse_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`order` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`order` (
  `order_id` VARCHAR(7) NOT NULL,
  `customer_id` VARCHAR(7) NOT NULL,
  `order_price` INT NOT NULL,
  `order_date` DATE NOT NULL,
  `order_time` TIME NOT NULL,
  `order_status` VARCHAR(50) NOT NULL,
  `delivery_address` VARCHAR(255) NOT NULL,
  `invoice_id` VARCHAR(7) NULL DEFAULT NULL,
  `journal_id` VARCHAR(7) NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  INDEX `journal_id` (`journal_id` ASC) VISIBLE,
  CONSTRAINT `order_management_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `ERP-Micro`.`customer` (`customer_id`),
  CONSTRAINT `order_management_ibfk_2`
    FOREIGN KEY (`journal_id`)
    REFERENCES `ERP-Micro`.`journal` (`journal_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`order_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`order_product` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`order_product` (
  `order_id` VARCHAR(7) NOT NULL,
  `product_id` VARCHAR(7) NOT NULL,
  `order_quantity` INT NOT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `order_product_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ERP-Micro`.`order` (`order_id`),
  CONSTRAINT `order_product_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `ERP-Micro`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`participation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`participation` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`participation` (
  `dept_ID` VARCHAR(7) NOT NULL,
  `project_ID` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`dept_ID`, `project_ID`),
  INDEX `project_ID` (`project_ID` ASC) VISIBLE,
  CONSTRAINT `participation_ibfk_1`
    FOREIGN KEY (`dept_ID`)
    REFERENCES `ERP-Micro`.`departments` (`dept_ID`),
  CONSTRAINT `participation_ibfk_2`
    FOREIGN KEY (`project_ID`)
    REFERENCES `ERP-Micro`.`project` (`project_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`pay_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`pay_category` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`pay_category` (
  `pay_cat_ID` VARCHAR(7) NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`pay_cat_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`pay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`pay` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`pay` (
  `pay_ID` VARCHAR(7) NOT NULL,
  `salary_ID` VARCHAR(7) NOT NULL,
  `pay_cat_ID` VARCHAR(7) NOT NULL,
  `employee_ID` VARCHAR(7) NOT NULL,
  `amount` DECIMAL(10,2) NULL DEFAULT '0.00',
  `date` DATE NOT NULL,
  PRIMARY KEY (`pay_ID`),
  INDEX `salary_ID` (`salary_ID` ASC) VISIBLE,
  INDEX `pay_cat_ID` (`pay_cat_ID` ASC) VISIBLE,
  INDEX `employee_ID` (`employee_ID` ASC) VISIBLE,
  CONSTRAINT `payment_ibfk_1`
    FOREIGN KEY (`salary_ID`)
    REFERENCES `ERP-Micro`.`basic_salary` (`salary_ID`),
  CONSTRAINT `payment_ibfk_2`
    FOREIGN KEY (`pay_cat_ID`)
    REFERENCES `ERP-Micro`.`pay_category` (`pay_cat_ID`),
  CONSTRAINT `payment_ibfk_3`
    FOREIGN KEY (`employee_ID`)
    REFERENCES `ERP-Micro`.`employee` (`employee_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`payment_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`payment_card` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`payment_card` (
  `card_ID` VARCHAR(7) NOT NULL,
  `card_number` VARCHAR(45) NOT NULL,
  `card_holder` VARCHAR(45) NOT NULL,
  `card_type` VARCHAR(45) NOT NULL,
  `card_issuer` VARCHAR(45) NOT NULL,
  `expiration` DATE NOT NULL,
  `bank_account_ID` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`card_ID`),
  INDEX `bank_account_ID` (`bank_account_ID` ASC) VISIBLE,
  CONSTRAINT `payment_card_ibfk_1`
    FOREIGN KEY (`bank_account_ID`)
    REFERENCES `ERP-Micro`.`bank_account` (`bank_account_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`payment` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`payment` (
  `payment_id` VARCHAR(7) NOT NULL,
  `payment_method` VARCHAR(50) NOT NULL,
  `order_id` VARCHAR(7) NOT NULL,
  `payment_price` INT NOT NULL,
  `payment_date` DATE NOT NULL,
  `payment_time` TIME NOT NULL,
  `payment_status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  CONSTRAINT `payment_management_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ERP-Micro`.`order` (`order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`permission` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`permission` (
  `dept_ID` VARCHAR(7) NOT NULL,
  `account_management` TINYINT NULL DEFAULT NULL,
  `account_period_management` TINYINT NULL DEFAULT NULL,
  `budget_management` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`dept_ID`),
  CONSTRAINT `permission_ibfk_1`
    FOREIGN KEY (`dept_ID`)
    REFERENCES `ERP-Micro`.`departments` (`dept_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`position_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`position_history` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`position_history` (
  `pos_history_ID` VARCHAR(7) NOT NULL,
  `employee_ID` VARCHAR(7) NOT NULL,
  `dept_ID` VARCHAR(7) NOT NULL,
  `position` VARCHAR(20) NULL DEFAULT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`pos_history_ID`),
  INDEX `employee_ID` (`employee_ID` ASC) VISIBLE,
  INDEX `dept_ID` (`dept_ID` ASC) VISIBLE,
  CONSTRAINT `position_history_ibfk_1`
    FOREIGN KEY (`employee_ID`)
    REFERENCES `ERP-Micro`.`employee` (`employee_ID`),
  CONSTRAINT `position_history_ibfk_2`
    FOREIGN KEY (`dept_ID`)
    REFERENCES `ERP-Micro`.`departments` (`dept_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`production`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`production` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`production` (
  `production_id` VARCHAR(7) NOT NULL,
  `product_id` VARCHAR(7) NOT NULL,
  `production_quantity` INT NOT NULL,
  `production_date` DATE NOT NULL,
  `production_time` TIME NOT NULL,
  `factory_id` VARCHAR(7) NOT NULL,
  `journal_id` VARCHAR(7) NOT NULL,
  `cost` INT NOT NULL,
  PRIMARY KEY (`production_id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `factory_id` (`factory_id` ASC) VISIBLE,
  INDEX `journal_id` (`journal_id` ASC) VISIBLE,
  CONSTRAINT `production_management_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ERP-Micro`.`product` (`product_id`),
  CONSTRAINT `production_management_ibfk_2`
    FOREIGN KEY (`factory_id`)
    REFERENCES `ERP-Micro`.`factory` (`factory_id`),
  CONSTRAINT `production_management_ibfk_3`
    FOREIGN KEY (`journal_id`)
    REFERENCES `ERP-Micro`.`journal` (`journal_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`status_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`status_history` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`status_history` (
  `sta_history_ID` VARCHAR(7) NOT NULL,
  `employee_ID` VARCHAR(7) NOT NULL,
  `status` ENUM('Employed', 'Leave', 'Retire') NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`sta_history_ID`),
  INDEX `employee_ID` (`employee_ID` ASC) VISIBLE,
  CONSTRAINT `status_history_ibfk_1`
    FOREIGN KEY (`employee_ID`)
    REFERENCES `ERP-Micro`.`employee` (`employee_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`supplier` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`supplier` (
  `supplier_id` VARCHAR(7) NOT NULL,
  `supplier_name` VARCHAR(255) NOT NULL,
  `supplier_phone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`supplier_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`supply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`supply` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`supply` (
  `product_id` VARCHAR(7) NOT NULL,
  `supplier_id` VARCHAR(7) NOT NULL,
  `cost` INT NOT NULL,
  `journal_id` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`product_id`, `supplier_id`),
  INDEX `supplier_id` (`supplier_id` ASC) VISIBLE,
  INDEX `journal_id` (`journal_id` ASC) VISIBLE,
  CONSTRAINT `supply_management_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ERP-Micro`.`product` (`product_id`),
  CONSTRAINT `supply_management_ibfk_2`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `ERP-Micro`.`supplier` (`supplier_id`),
  CONSTRAINT `supply_management_ibfk_3`
    FOREIGN KEY (`journal_id`)
    REFERENCES `ERP-Micro`.`journal` (`journal_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`transaction` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`transaction` (
  `trans_ID` VARCHAR(7) NOT NULL,
  `journal_ID` VARCHAR(7) NOT NULL,
  `account_code` VARCHAR(7) NOT NULL,
  `trans_date` DATE NOT NULL,
  `debit` DECIMAL(10,2) NOT NULL,
  `credit` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`trans_ID`),
  INDEX `journal_ID` (`journal_ID` ASC) VISIBLE,
  INDEX `account_code` (`account_code` ASC) VISIBLE,
  CONSTRAINT `transaction_ibfk_1`
    FOREIGN KEY (`journal_ID`)
    REFERENCES `ERP-Micro`.`journal` (`journal_ID`),
  CONSTRAINT `transaction_ibfk_2`
    FOREIGN KEY (`account_code`)
    REFERENCES `ERP-Micro`.`account` (`account_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ERP-Micro`.`use_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP-Micro`.`use_account` ;

CREATE TABLE IF NOT EXISTS `ERP-Micro`.`use_account` (
  `account_code` VARCHAR(7) NOT NULL,
  `budget_ID` VARCHAR(7) NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`account_code`, `budget_ID`),
  INDEX `budget_ID` (`budget_ID` ASC) VISIBLE,
  CONSTRAINT `use_account_ibfk_1`
    FOREIGN KEY (`account_code`)
    REFERENCES `ERP-Micro`.`account` (`account_code`),
  CONSTRAINT `use_account_ibfk_2`
    FOREIGN KEY (`budget_ID`)
    REFERENCES `ERP-Micro`.`budget` (`budget_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
